# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AArANoBxfzSUbdLMVaI5dH3qtVC-KW0P
"""

print("hallo world")